#!/bin/bash

set -exou pipefail

echo "Which disk to install on ?"
read DISK

# Simulates manual inputs to fdisk
# The sed command strips the comment
# Blank lines use the default option
# Taken from https://superuser.com/a/984637
sed -e 's/\s*\([\+0-9a-zA-Z]*\).*/\1/' << EOF | fdisk "$DISK"
    g # new GPT partition table
    n # new partition
    # default - partition number #1
    # default - first sector
    +1G # efi partition size
    t # change partition type
    1 # select "EFI system" partition type
    n # new partition
    # default - partition number #2
    # default - first sector
    # default - last sector
    t # change partition type
    # default - partition number #2
    23 # select "Linux root (x86-64)" partition type
    p # print the in-memory partition table
    w # write the partition table
    q # and we're done
EOF

cryptsetup luksFormat "$DISK"2
cryptsetup open "$DISK"2 root
mkfs.ext4 /dev/mapper/root
mount /dev/mapper/root /mnt

mkfs.fat -F 32 "$DISK"1
mount --mkdir "$DISK"1 /mnt/efi

pacstrap -K /mnt base linux linux-firmware

cp -r chrooted /mnt/arch-install

arch-chroot /mnt /bin/bash << EOF
    cd /arch-install
    ./chrooted-arch-install
EOF
