#!/bin/bash

set -eou pipefail
. chrooted/lib

echo "WARNING : This script does not care about your data.
New partitions will be created and the existing data will be permanently lost.
Press ctrl+c right now if this is not ok.
Which disk to install on ?"
read DISK
while ! [ -e "$DISK" ]; do
    echo "$DISK does not exist"
    read DISK
done

echo "Hostname ?"
read HOSTNAME
# Regex from https://stackoverflow.com/a/106223
while ! [[ "$HOSTNAME" =~ ^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$ ]]; do
    echo "Invalid hostname, must be valid as per RFC 1123"
    read HOSTNAME
done

echo "Username ?"
read USERNAME
# Regex from https://unix.stackexchange.com/a/507591
while ! [[ "$USERNAME" =~ ^([A-Za-z][A-Za-z0-9._-]*)$ ]]; do
    echo "Invalid username, must start with a letter and contain only letters, digits, dots, dashes and underscores"
    read USERNAME
done

read -p $'Password ?\n' -s PASSWORD
read -p $'Verify password\n' -s PASSWORD_VERIFY
while [ "$PASSWORD" != "$PASSWORD_VERIFY" ]; do
    echo "Passwords do not match"
    read -p $'Password ?\n' -s PASSWORD
    read -p $'Password again ?\n' -s PASSWORD_VERIFY
done

# Simulates manual inputs to fdisk
# The sed command strips the comment
# Blank lines use the default option
# Taken from https://superuser.com/a/984637
# Here we setup partitions as per
# https://wiki.archlinux.org/title/Dm-crypt/Encrypting_an_entire_system#LUKS_on_a_partition_with_TPM2_and_Secure_Boot
sed -e 's/\s*\([\+0-9a-zA-Z]*\).*/\1/' << EOF | fdisk "$DISK"
    g # new GPT partition table
    n # new partition
    # default - partition number #1
    # default - first sector
    +1G # efi partition size
    t # change partition type
    1 # select "EFI system" partition type
    n # new partition
    # default - partition number #2
    # default - first sector
    # default - last sector
    t # change partition type
    # default - partition number #2
    23 # select "Linux root (x86-64)" partition type
    p # print the in-memory partition table
    w # write the partition table
    q # and we're done
EOF

EFI_PART_PATH=$(get_disk_partition_path "$DISK" 1)
LUKS_PART_PATH=$(get_disk_partition_path "$DISK" 2)
LUKS_DEVICE_NAME=cryptlvm
LVM_GROUP_NAME=volumegroup
ROOT_PATH=/dev/$LVM_GROUP_NAME/root

echo "Wait while encryption is enabled..."

# This passphrase will be removed after first boot when enrolling TPM
echo -n "passphrase" | cryptsetup luksFormat $LUKS_PART_PATH -
echo -n "passphrase" | cryptsetup luksAddKey $LUKS_PART_PATH chrooted/luks-key.txt -d -
cryptsetup open $LUKS_PART_PATH $LUKS_DEVICE_NAME -d chrooted/luks-key.txt

# Setup LVM layer
pvcreate /dev/mapper/$LUKS_DEVICE_NAME
vgcreate $LVM_GROUP_NAME /dev/mapper/$LUKS_DEVICE_NAME
lvcreate -l 100%FREE -n root $LVM_GROUP_NAME
lvreduce -L -256M $LVM_GROUP_NAME/root

mkfs.ext4 "$ROOT_PATH"
mount "$ROOT_PATH" /mnt

mkfs.fat -F 32 "$EFI_PART_PATH"
mount --mkdir "$EFI_PART_PATH" /mnt/efi

pacstrap -K /mnt base linux linux-firmware lvm2 cronie sbctl sudo

cp -r chrooted /mnt/arch-install
chmod 700 /mnt/arch-install

arch-chroot /mnt bash -c "/arch-install/chrooted-arch-install \
    $HOSTNAME \
    $USERNAME \
    $PASSWORD \
    $LUKS_PART_PATH \
    $LUKS_DEVICE_NAME \
    $ROOT_PATH"

echo "Done ! You can reboot and use the system now."
