#!/bin/bash

set -exou pipefail
cd /arch-install
. ./lib

# Set hostname
echo "Hostname ?"
read hostname
echo $hostname > /etc/hostname

# Create user account
echo "Username ?"
read username
# See groups here https://wiki.archlinux.org/title/Users_and_groups#User_groups
useradd -m $username --groups adm,log,rfkill,sys
echo "$username password ?"
loop_until_success "passwd $username"

# Configure mkinitcpio
sed -i "s/^HOOK.*$/HOOKS=(systemd autodetect microcode modconf keyboard sd-vconsole block sd-encrypt filesystems fsck)/" /etc/mkinitcpio.conf

cat > /etc/mkinitcpio.d/linux.preset <<EOF
ALL_kver="/boot/vmlinuz-linux"
PRESETS=('default' 'fallback')
default_image="/boot/initramfs-linux.img"
default_uki="/efi/EFI/Linux/arch-linux.efi"
fallback_image="/boot/initramfs-linux-fallback.img"
fallback_options="-S autodetect"
EOF

# Set kernel command line
LUKS_PART_PATH=$(cryptsetup status root | grep device | cut -d ":" -f 2 | xargs)
LUKS_PART_UUID=$(blkid -s UUID -o value $LUKS_PART_PATH)
echo "rd.luks.name=$LUKS_PART_UUID=root rootflags=rw,nodev,noatime" > /etc/kernel/cmdline

# Install systemd-boot's efi boot manager
bootctl install

# Generate initramfs
mkinitcpio -P


### From this point the computer should boot and be usable


# Create secure boot keys
sbctl create-keys

# Enroll secure boot keys
# If including firmware certificates (-f) fails,
# try without
set +e
sbctl enroll-keys -m -f
ENROLL_RES=$?
set -e
if [ "$ENROLL_RES" -ne 0 ]; then
    sbctl enroll-keys -m
fi

# Sign boot files
sbctl sign -s /efi/EFI/BOOT/BOOTX64.EFI
sbctl sign -s /efi/EFI/systemd/systemd-bootx64.efi
sbctl sign -s /efi/EFI/Linux/arch-linux.efi

# Enroll TPM
systemd-cryptenroll $LUKS_PART_PATH --recovery-key > /arch-install/luks-recovery-key.txt
systemd-cryptenroll $LUKS_PART_PATH --wipe-slot=empty --tpm2-device=auto --tpm2-pcrs=7+15:sha256=0000000000000000000000000000000000000000000000000000000000000000 # --tpm2-with-pin=yes

# pacman config
sed -i "s/#Color/Color/" /etc/pacman.conf
sed -i "s/#\[multilib\]/\[multilib\]\nInclude = \/etc\/pacman.d\/mirrorlist/" /etc/pacman.conf

# Use all available cores for aur packages compilation
sed -i 's/#MAKEFLAGS="-j2"/MAKEFLAGS="-j'$(nproc)'"/' /etc/makepkg.conf

echo "kernel.sysrq=1 # Enable REISUB" > /etc/sysctl.d/99-sysctl.conf

# base
packages="$(get_cpu_brand)-ucode fuse2 htop libdbusmenu-glib man-db man-pages ncdu nvtop p7zip pacman-contrib pyenv reflector rsync screen texinfo unrar unzip vim wget zip"

# networking
packages="${packages} ethtool networkmanager openssh nmap nss-mdns wireguard-tools"

# audio
packages="${packages} pipewire lib32-pipewire pipewire-audio pipewire-alsa pipewire-pulse pipewire-jack lib32-pipewire-jack wireplumber"

# fonts
packages="${packages} noto-fonts noto-fonts-cjk noto-fonts-emoji"

# other apps
packages="${packages} firefox mpv qbittorrent"

# printers
packages="${packages} cups system-config-printer"

# dev
packages="${packages} base-devel git cmake"

# KDE apps
packages="${packages} ark bluedevil breeze breeze-gtk dolphin drkonqi gwenview kcalc kde-gtk-config kdeplasma-addons kfind kinfocenter konsole kpipewire kscreen kscreenlocker kwallet-pam kwalletmanager kwin kwrite plasma-desktop plasma-nm plasma-pa polkit-kde-agent print-manager sddm-kcm spectacle systemsettings xdg-desktop-portal-kde"

pacman -Syu --needed $packages

echo "$username ALL=(ALL:ALL) ALL" > /etc/sudoers.d/$username

# Set avahi conf
sed -i 's/hosts:.*/hosts: mymachines mdns_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] files myhostname dns/' /etc/nsswitch.conf

systemctl enable avahi-daemon bluetooth cups.socket fstrim.timer NetworkManager reflector.timer sddm systemd-timesyncd

cp -r etc /

# Set timezone
ln -sf /usr/share/zoneinfo/Europe/Paris /etc/localtime

# Set hardware clock to current time
hwclock --systohc

# Activate en_DK.UTF-8 locale
# en_DK to have english with normal measurement units and formats for time, date, etc
echo "en_DK.UTF-8 UTF-8" > /etc/locale.gen
locale-gen
echo "LANG=en_DK.UTF-8" > /etc/locale.conf

# Set keymap for console
cat > /etc/vconsole.conf <<EOF
KEYMAP=fr
XKBLAYOUT=fr
EOF

# Set keymap for x11 stuff like sddm
localectl set-x11-keymap fr

echo "Done !"
echo "Don't forget to store your disk encryption recovery key somewhere safe."
echo "You can reboot and use the system now."
