#!/bin/bash

set -eou pipefail
cd /arch-install
. ./lib

cp -r etc /

# Set timezone
ln -sf /usr/share/zoneinfo/Europe/Paris /etc/localtime

# Set hardware clock to current time
hwclock --systohc

# Activate en_DK.UTF-8 locale
# en_DK to have english with normal measurement units and formats for time, date, etc
locale-gen

# Set hostname
echo "Hostname ?"
read hostname
echo $hostname > /etc/hostname

# Create user account
echo "Username ?"
read username
# See groups here https://wiki.archlinux.org/title/Users_and_groups#User_groups
useradd -m $username --groups adm,log,rfkill,sys,wheel
echo "$username password ?"
loop_until_success "passwd $username"
echo "$username ALL=(ALL:ALL) ALL" > /etc/sudoers.d/$username

# Configure mkinitcpio
sed -i "s/^HOOK.*$/HOOKS=(base systemd autodetect microcode modconf kms keyboard keymap sd-vconsole block sd-encrypt filesystems fsck)/" /etc/mkinitcpio.conf

# Set kernel command line
LUKS_PART_PATH=$(cryptsetup status root | grep device | cut -d ":" -f 2 | xargs)
LUKS_PART_UUID=$(blkid -s UUID -o value $LUKS_PART_PATH)
echo "rd.luks.name=$LUKS_PART_UUID=root rootflags=rw,nodev,noatime" > /etc/kernel/cmdline

# Install systemd-boot's efi boot manager
bootctl install

# Generate initramfs now because we need the efi files to sign them later with sbctl
mkinitcpio -P


### From this point the computer should boot and be usable


# Check that secure boot is in setup mode and that a TPM is available
sbctl status | grep -q "Setup Mode:.*Enabled"
if [ $? -eq 0 ] && [ -e /dev/tpm0 ]; then
    # Create secure boot keys
    sbctl create-keys

    # Enroll secure boot keys
    # If including firmware certificates (-f) fails,
    # try without
    set +e
    sbctl enroll-keys -m -f
    ENROLL_RES=$?
    set -e
    if [ "$ENROLL_RES" -ne 0 ]; then
        sbctl enroll-keys -m
    fi

    # Sign .efi boot files
    sbctl sign -s /efi/EFI/BOOT/BOOTX64.EFI
    sbctl sign -s /efi/EFI/systemd/systemd-bootx64.efi
    sbctl sign -s /efi/EFI/Linux/arch-linux.efi

    # Secure boot has to be enabled for TPM enrollement to work
    # So we tell cron to run a script doing that on first boot
    echo "@reboot /arch-install/firstboot $LUKS_PART_PATH $username" | crontab -
else
    echo "Secure boot is not is setup mode, or there is no TPM in the system.
Skipping secure boot and TPM setup.
Press Enter to continue..."
    read
fi

# pacman config
sed -i "s/#Color/Color/" /etc/pacman.conf
sed -i "s/#\[multilib\]/\[multilib\]\nInclude = \/etc\/pacman.d\/mirrorlist/" /etc/pacman.conf

# Use all available cores for aur packages compilation
sed -i 's/#MAKEFLAGS="-j2"/MAKEFLAGS="-j'$(nproc)'"/' /etc/makepkg.conf

# base
packages="$(get_cpu_brand)-ucode fuse2 htop libdbusmenu-glib man-db man-pages ncdu nvtop p7zip pacman-contrib pyenv reflector rsync screen texinfo unrar unzip vim wget zip"

# networking
packages="${packages} ethtool networkmanager openssh nmap nss-mdns wireguard-tools"

# audio
packages="${packages} pipewire lib32-pipewire pipewire-audio pipewire-alsa pipewire-pulse pipewire-jack lib32-pipewire-jack wireplumber"

# fonts
packages="${packages} noto-fonts noto-fonts-cjk noto-fonts-emoji"

# other apps
packages="${packages} firefox mpv qbittorrent"

# printers
packages="${packages} cups system-config-printer"

# dev
packages="${packages} base-devel git cmake"

# KDE apps
packages="${packages} ark bluedevil breeze breeze-gtk dolphin drkonqi gwenview kcalc kde-gtk-config kdeplasma-addons kfind kinfocenter konsole kpipewire kscreen kscreenlocker kwallet-pam kwalletmanager kwin kwrite plasma-desktop plasma-nm plasma-pa polkit-kde-agent print-manager sddm-kcm spectacle systemsettings xdg-desktop-portal-kde"

pacman -Syu --needed $packages

# Set avahi conf
sed -i 's/hosts:.*/hosts: mymachines mdns_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] files myhostname dns/' /etc/nsswitch.conf

systemctl enable avahi-daemon.service bluetooth.service cronie.service cups.socket fstrim.timer NetworkManager.service reflector.timer sddm.service systemd-timesyncd.service

echo "On first OS boot, an encryption key will be generated and stored in the TPM.
A recovery key will also be generated and saved to /home/$username/luks-recovery-key.txt.
Make sure to save it somewhere safe.
The passphrase that must be entered on first boot is \"passphrase\".
This dummy passphrase will be wiped after first boot, and the disk will be automatically decrypted afterwards."
