#!/bin/bash

set -eou pipefail

set +e
sbctl status | grep -q "Secure Boot:.*Enabled"
if [ $? -ne 0 ] || [ ! -e /dev/tpm0 ]; then
    exit 1
fi
set -e

DEVICE=$1
USERNAME=$2
RECOVERY_KEY_PATH=/home/$USERNAME/luks-recovery-key.txt

systemd-cryptenroll "$DEVICE" --unlock-key-file=/arch-install/luks-key.txt --recovery-key > "$RECOVERY_KEY_PATH"
systemd-cryptenroll "$DEVICE" --unlock-key-file=/arch-install/luks-key.txt --wipe-slot=password --tpm2-device=auto --tpm2-pcrs=7+15:sha256=0000000000000000000000000000000000000000000000000000000000000000

chown $USERNAME:$USERNAME $RECOVERY_KEY_PATH
chmod 600 $RECOVERY_KEY_PATH

rm -r /arch-install
crontab -r
systemctl disable --now cronie.service
pacman -Rs --noconfirm cronie
