#!/bin/bash

function loop_until_success
{
    set +e
    eval $1
    while [ $? -ne 0 ];
    do
        eval $1
    done
    set -e
}

function get_cpu_brand
{
    lscpu | grep -qe "Model name:.*AMD"
    if [ $? -eq 0 ]; then
        echo "amd"
        return 0
    fi

    lscpu | grep -qe "Model name:.*Intel"
    if [ $? -eq 0 ]; then
        echo "intel"
    fi
}

function get_disk_partition_path
{
    echo $(blkid | grep -e "$1.*$2:" | cut -d ":" -f 1)
}
